version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: dotnet/sdk
        update-types: ["version-update:semver-major"]
    groups:
      all-docker:
        patterns:
          - "*"
  # spritely/build/container uses other spritely actions, some of which use the container produced by this repo as a devcontainer
  # Therefore enabling the code below would create a circular dependency, so build version updates are manual in this repo
  # - package-ecosystem: github-actions
  #   directories:
  #     - /
  #     - "**/*"
  #   schedule:
  #     interval: daily
  #   groups:
  #     all-github-actions:
  #       patterns:
  #         - "*"
